paths: 
  /api/products:
    get:
      summary: Get all products
      tags:
        - Products
      responses: 
        "200":
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        "500":
          description: Error interno en el servidor
    post:
      tags: 
        - Products
      security: 
        -bearerAuth: []
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title: 
                  type:  string
                  required: true
                description: 
                  type:  string
                  required: true
                price: 
                  type:  number
                  required: true
                code: 
                  type:  string
                  required: true
                thumbnails:
                  type: string
                status:
                  type: boolean
                category:
                  type: string
                  required: true
                stock:
                  type: number
                  required: true
      responses: 
        '200':
          description: Successfull operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
  /api/products/{productId}:
    get:
      summary: Get a product by ID
      tags:
        - Products
      parameters: 
        - name: productId
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
      responses: 
        "200":
          description: Successfull operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        "500":
          description: Error interno en el servidor
    put:
      tags: 
        - Products
      summary: Update a product by ID
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                title:
                  type: string
                  required: true
                category:
                  type: string
                  required: true
                code:
                  type: string
                description:
                  type: string
                price:
                  type: number
                  required: true
                stock:
                  type: number
                  required: true
                thumbnail:
                  type: string
                status:
                  type: boolean
              required:
                - title
                - category
                - price
                - stock
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      summary: Delete a product by ID
      tags:
        - Products
      parameters: 
        - name: productId
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
      responses: 
        "200":
          description: Successfull operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        "500":
          description: Error interno en el servidor



components:
  schemas:
    Products:
      type: object
      properties:  
        _id: 
          type: objectId
          description: Id autogenerado por MongoDB
        title:
          type: string
          description: Nombre del producto
        description: 
          type: string
          description: Descripcion del producto
        price:
          type: number
          description: Precio del producto
        thumbnails:
          type: string
          description: Imagen o lista de Imagenes del producto
        status:
          type: boolean
          description: 
        code:
          type: string
          description: Codigo del producto
        stock:
          type: number
          description: Stock del producto
        category:
          type: string
          description: Categoria del producto
      required:
        - title
        - description
        - price
        - status
        - code
        - stock
        - category
  securitySchemes: 
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT